### ISSUE TITLE
Content Type Clone ignores Field Groups

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/field_group#13]
Cross-referencing because I haven't been able to figure which module this error should be fixed in (or how to fix it):

https://github.com/backdrop-contrib/content_type_clone/issues/2

**Comment by herbdool** [comment]
Was there a similar problem in D7?

**Comment by laryn** [comment]
I haven't used it in D7 but will do some testing.

**Comment by kswan** [comment]
It is likely this is related to https://github.com/backdrop-contrib/field_group/commit/b3cfaee08523e68a0c477e2719b1a35274505b2a
The field_group name key was re-ordered by that commit.

**Comment by herbdool** [comment]
@kswan I don't think that fixes this. I've tested cloning after fixing the field_group issue. Still no field_group. Likely because it is handled differently from fields in general.

**Comment by herbdool** [comment]
Might need to implement `field_group_info_groups()` and then clone each field group with the new bundle name.

**Comment by herbdool** [comment]
In my previous comment I meant that `field_group_info_groups()` should be implemented in content type clone.

**Comment by laryn** [comment]
I'll close this here and transcribe your comment into the cross-referenced issue linked in the first comment.
