### ISSUE TITLE
Field Groups don't display on Paragraphs

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/field_group#16]
Cross-referencing:
https://github.com/backdrop-contrib/paragraphs/issues/26

The groups show up in the Manage Display screen, but not the front end display. I spent some time looking and haven't solved it. Any ideas or direction is welcome.

**Comment by kelizoliva** [comment]
I can confirm this issue.

**Comment by findlabnet** [comment]
On template level of Paragraphs we can see `$content` variable contain already rendered HTML string instead of array of content items (e.g. fields).
This make separate fields not templatable at all. But it is issue of Paragraphs module, not Field Groups IMHO.

**Comment by laryn** [comment]
Thanks, will close this one.
