### ISSUE TITLE
Add HTML details element

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/field_group#18]
Just following https://github.com/backdrop/backdrop-issues/issues/324 and wondering if we add it as an option here too.

**Comment by laryn** [comment]
I was just going to add this as an issue and see you've already noted it. 👍

**Comment by herbdool** [comment]
@laryn I've add HTML detail https://github.com/backdrop-contrib/field_group/commit/b6bf0adc9e43cdd827d8da5f7709cc6c8a16d10c. Want to test before I release? Seems to be working okay.

**Comment by laryn** [comment]
I did some basic testing and it looks good. I tried adding `$form['label']['#required'] = TRUE;` (to get the asterisk to show up) but it didn't seem to take.

**Comment by herbdool** [comment]
@laryn thanks! I've added the JS necessary for the required functionality to work for Details. I never knew about this before. It seems like it works even better than using fieldset - since it'll add an asterix (which even in D7 fieldset doesn't seem to do that).
