### ISSUE TITLE
Ability to add classes on vertical tabs

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/field_group#21]
Neither the classes that are added in the UI nor classes that are added in code seem to be applied to vertical tabs within a vertical tabs group.

**Comment by olafgrabienski** [comment]
Hm, vertical tab classes are working for me. Below are two example screenshots. Not sure if that's the place you were referring to.

**Manage display:**

<img width="864" alt="backdrop-fieldgroup-classes-1" src="https://user-images.githubusercontent.com/14188307/138563394-112020cb-dec6-4928-80c0-09675b02f52b.png">

**HTML output:**

<img width="364" alt="backdrop-fieldgroup-classes-2" src="https://user-images.githubusercontent.com/14188307/138563396-3bfc03cc-794d-4957-8ce3-d16c9620c75a.png">

**Comment by laryn** [comment]
@olafgrabienski That is the place I'm referring to but the markup I get looks completely different (with no classes added on the front end, even though they show on the backend as in your first screenshot). Are you on `1.0.4`?

![vtabs](https://user-images.githubusercontent.com/871421/138594285-8cc60370-923c-47e2-a3cf-ac205484bc1c.png)

**EDIT**: I see, you are looking at the window with the tab content and I'm referring to the tab itself!

**Comment by laryn** [comment]
My use case is trying to add icons on the vertical tabs via CSS.

**Comment by olafgrabienski** [comment]
> I see, you are looking at the window with the tab content and I'm referring to the tab itself!

You're right! So, technically it might work as expected (not sure), but the classes aren't necessarily at the place where one would expect them. Actually, both places can be useful.

As a workaround to add icons on the vertical tabs via CSS (if the tab order is predictable and won't change often) maybe choose selectors based on their position? Something like this:

```
.vertical-tab-item.first {
  background: url(icon-a.png) no-repeat;
}
.vertical-tab-item:nth-of-type(2) {
  background: url(icon-b.png) no-repeat;
}
.vertical-tab-item:nth-of-type(3) {
  background: url(icon-c.png) no-repeat;
}
.vertical-tab-item.last` {
  background: url(icon-d.png) no-repeat;
}
```

**Comment by herbdool** [comment]
Is this a bug or just unexpected way of implementing? Not sure what needs to be done here.

**Comment by laryn** [comment]
I guess that's a question for the maintainer. ;) 

I was expecting to be able to style the tab/trigger but I've adapted this particular project and styled the content of those tabs instead of the tabs themselves. I guess it's up to you as to whether you think the ability to add styles to tabs is of value.

**Comment by herbdool** [comment]
I've never used the vertical tabs here. I suspect it works as it should.

Can we change this to an enhancement then?

**Comment by herbdool** [comment]
I think this is an issue for core since that's where vertical tabs are actually implemented and themed.
