### ISSUE TITLE
field_group table is missing in hook_field_attach_rename_bundle

### ISSUE THREAD

**Issue by crackerizer** [backdrop-contrib/field_group#25]
Renaming node type causes an error in hook_field_attach_rename_bundle because field_group table is moved to config.

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'table.field_group' doesn't exist: UPDATE {field_group} SET bundle = :bundle WHERE bundle = :old_bundle AND entity_type = :entity_type; Array ( [:bundle] => bundle_name [:old_bundle] => bundle_name [:entity_type] => node ) in field_group_field_attach_rename_bundle() (line 1476 of /modules/field_group/field_group.module).

**Comment by herbdool** [comment]
A bit of a delay but I've fixed it (working for me in testing at least).
