### ISSUE TITLE
Move all theme functions into a field_group.theme.inc file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/field_group#32]
Adding some issues to match commits from the core PR, in the hopes of getting these changes into contrib first. :) 

Note to self: see commit b80cf8ffc875160a1042c7a038b04351a006719a

**Comment by herbdool** [comment]
Duplicate. https://github.com/backdrop-contrib/field_group/issues/28

**Comment by jenlampton** [comment]
how'd I miss that? :( sorry for the noise.
