### ISSUE TITLE
Undefined index: label_element in field_group_field_group_format_settings

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/field_group#38]
When I visit the Manage display page of a content type with a Details field group, I get the following PHP notice in DBlog:

> Undefined index: label_element in field_group_field_group_format_settings() (line 597 of PATH-TO/modules/field_group/field_group.module).

**Comment by herbdool** [comment]
@olafgrabienski I'm unable to replicate this. Perhaps I'm missing some steps.

**Comment by olafgrabienski** [comment]
Thanks for looking into this, @herbdool . I've just reproduced the issue on a vanilla demo site. Actually, I didn't get exactly the same message, but it sounds related (I guess it differs because of the new module release, or because of a different PHP version of the demo site):

> Warning: Undefined array key "label_element" in field_group_field_group_format_settings_alter() (line 899 of /var/lib/tugboat/backdrop/modules/field_group/field_group.groups.inc).

Steps to reproduce:

- Install end enable Field Group.
- Go to the Default display form of the Post content type (`admin/structure/types/manage/post/display/default`).
- Add a new group (Name: Test group, Format: Details, default settings), and save the form.
- Go to `admin/reports/dblog`, and find the PHP message.

**Comment by herbdool** [comment]
Fixed.
