### ISSUE TITLE
Make group machine name the same as field machine names

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/field_group#4]
Field machine names are generated automatically based on the field label, and can be edited thereafter. Group machine names have to be entered manually. I think this can be improved to better match core...

![screenshot-2018-6-28 portfolio item packweb](https://user-images.githubusercontent.com/2385329/42032163-651b9e68-7ae1-11e8-9c4d-df342dc04187.png)

**Comment by herbdool** [comment]
@BWPanda I took a stab at it in this PR https://github.com/backdrop-contrib/field_group/pull/8. It seems to work well enough though behind the scenes it still has to use the field_group validation and I had to add a dummy callback for machine name (the callback seems like it can only validate a name globally and not per content type/view mode.
