### ISSUE TITLE
jQuery.isFunction() is deprecated

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/field_group#46]
I'm scanning a project for deprecated jQuery code and found this one:

> JQMIGRATE: jQuery.isFunction() is deprecated

 - https://api.jquery.com/jQuery.isFunction/
> As of jQuery 3.3, `jQuery.isFunction()` has been deprecated. In most cases, its use can be replaced by `typeof x === "function"`.

https://github.com/backdrop-contrib/field_group/blob/1.x-1.x/js/field_group.js#L25

**Comment by laryn** [comment]
I linked a PR for review.

**Comment by herbdool** [comment]
Thanks @laryn
