### ISSUE TITLE
Bug in field_groups.js

### ISSUE THREAD

**Issue by onyxnz** [backdrop-contrib/field_group#48]
The API changed for JQuery UI 1.9+, so line 104 should be 

$firstErrorItem = $(this).parent().accordion('option', 'active' , i);

otherwise an error is encountered:
Uncaught Error: no such method 'activate' for accordion widget instance

cf https://stackoverflow.com/questions/1899307/jquery-ui-accordion-activate
Cheers!

**Comment by herbdool** [comment]
Steps to recreate:

1. Add an accordion group, and two accordion items to a content type. 
2. In each accordion item but a field. 
3. Make either one of those fields required. 
4. Go to create a node.
5. Leave the required field blank and attempt to save.
6. Console shows error.
