### ISSUE TITLE
Errors with configuration export/import

### ISSUE THREAD

**Issue by mazzech** [backdrop-contrib/field_group#5]
I have created a content type in example1.com and wanted to export/import the entire config in example2.com. I got errors for all the five field groups I used in my content type during import:

`The attributes for group_name, entity_type, bundle, mode do not match the file name "field_group.field_group.node.blg.form.group_bulletlist".`

Also tried to import one of the json files with single import:
```
{
    "_config_name": "field_group.field_group.node.blg.form.group_bulletlist",
    "group_name": "group_bulletlist",
    "entity_type": "node",
    "bundle": "blg",
    "mode": "form",
    "children": [
        "field_bullet_list_title",
        "field_multifield_text"
    ],
    "parent_name": "",
    "weight": "8",
    "label": "Bullet List",
    "format_type": "fieldset",
    "format_settings": {
        "label": "Bullet List",
        "instance_settings": {
            "required_fields": 1,
            "id": "",
            "classes": "group-bulletlist field-group-fieldset",
            "description": ""
        },
        "formatter": "collapsed"
    },
    "collapsible": true,
    "collapsed": false
}
```
Could there be in incompatibiliy with configuration settings...? (BTW it's my first creation of any Github issue for Backdrop CMS, let me know if somethings wrong or missing!)

**Comment by jenlampton** [comment]
Hi @mazzech, thanks for reporting this issue. I'm seeing the same thing on my site:
```
The attributes for group_name, entity_type, bundle, mode do not match the file name "field_group.field_group.node.biblio_pub.form.group_biblio_authors".
```

**Comment by mazzech** [comment]
Hi @jenlampton I managed to find a temporary workaround: disable the field group module before import, re-enable it after, and the field groups are there:-)

**Comment by jenlampton** [comment]
I've got a PR up at https://github.com/backdrop-contrib/field_group/pull/6 that fixes this issue.

**Comment by herbdool** [comment]
Merged. Thanks @mazzech for reporting and thanks for fixing @jenlampton!

**Comment by jenlampton** [comment]
Wow, that was fast!  Thanks @herbdool !!!

**Comment by mazzech** [comment]
Thank you @herbdool for the fix. Good to see you on the core maintainer list, congratulations!
