### ISSUE TITLE
Delete link doesn't work on Manage Displays

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/field_group#7]
I'm able to delete groups on the manage fields tab, but on manage displays the Delete link takes me directly back to the configure tab, without deleting the group. 

Steps to Reproduce:
1) Add fields to form
2) Add field_group to form 
3) clone field groups to Displays
4) delete field group from form (works!)
5) delete field group from Display (fails!)

**Comment by herbdool** [comment]
@jenlampton I'm testing but I can't replicate the issue. I tried it with the latest dev version (which I think is the same as the 1.x-1.0.2 release).

**Comment by jenlampton** [comment]
Hm, let me try with the latest dev version. I think I ended up doing a config sync / flush all caches and it sorted itself out? seemed like some kind of menu router mixup.
